version: '3.4'
services:
        flask_app:
                image: zgchuck/flask_app
                build:
                        context: ./app
                ports:
                        - 5002:5002
                secrets:
                        - db_pass
                        - db_user
                        - db_name
                environment:
                        MYSQL_PASSWORD: /run/secrets/db_pass       
                        MYSQL_DATABASE: /run/secrets/db_name
                        MYSQL_USER: /run/secrets/db_user
                networks:
                        - flask

        flask-mysql-service:
                image: zgchuck/flask_mysql
                build:
                        context: ./mysql
                ports:
                        - 3306:3306
                secrets:
                        - db_root_pass
                        - db_pass
                        - db_user
                        - db_name
                environment:
                        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
                        MYSQL_PASSWORD_FILE: /run/secrets/db_pass       
                        MYSQL_DATABASE_FILE: /run/secrets/db_name
                        MYSQL_USER_FILE: /run/secrets/db_user
                networks:
                        - flask

secrets:
        db_name:
                file: ./secrets/db_name.txt
        db_user:
                file: ./secrets/db_user.txt
        db_pass:
                file: ./secrets/db_pass.txt
        db_root_pass:
                file: ./secrets/mysql_root_pass.txt

networks:
        flask:

