apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    name: flask-app-service
    app: flask
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
  selector:
    name: flask-app-pod
    app: flask
